name: Bug Report
title: '[Bug]: '
description: File a bug report
labels: ["bug"]
body:
- type: markdown
  attributes:
    value: 
      Thanks for taking the time to fill out this bug report. It will greatly assist us in accurately identifying the issue.
- id: what-happened
  type: textarea
  attributes:
    description: Please tell us what's not working as expected. Please include callstacks and error messages if possible.
    label: What happened and how to repro
    placeholder: Please describe the issue you encountered, and minimal steps needed to reproduce the bug.
  validations:
    required: true

- id: runtime-version
  type: input
  attributes:
    description: Please enter the Runtime version you are using. (e.g. 114.0.1823.79)
    label: Runtime Version
  validations:
    required: true
- id: sdk-version
  type: input
  attributes:
    description: Please enter the SDK version you are using. (e.g. 1.0.1905-prerelease)
    label: SDK Version
  validations:
    required: true

- id: framework
  type: dropdown
  attributes:
    description: What framework are you using?
    label: Framework
    options:
    - Please select
    - WPF
    - Win32
    - Winform
    - UWP/WinUI2
    - WinUI3
    - Unity Plugin
  validations:
    required: true
- id: os
  type: checkboxes
  attributes:
    description: What operating system are you using?
    label: Operating System
    options:
    - label: Windows 10
    - label: Windows 11
    - label: Earlier than Windows 10 (deprecated)
    - label: Windows Server
    - label: Xbox
    - label: Hololens
    - label: Other
  validations:
    required: true
- id: os-version
  type: input
  attributes:
    description: Please enter the OS version you are using. (e.g., 22H2, 21H1, etc.)
    label: OS Version
  validations:
    required: false
- id: repro-steps
  type: textarea
  attributes:
    description: Minimal steps needed to reproduce the bug. Please be clear on what the expected behavior is V.S. what the actual behavior is. Please provide a minimal sample app that demonstrates the issue, if possible.
    label: Repro steps and sample app
  validations:
    required: false
- id: regression
  type: dropdown
  attributes:
    description: Was this working before, but has regressed?
    label: Regression
    options:
    - No, first time seeing this
    - Regression in Runtime
    - Regression in SDK
    - Don't know
  validations:
    required: true
- id: last-working-version
  type: input
  attributes:
    description: If this is a regression, what was the last working version of SDK and Runtime? (e.g. SDK 1.0.1774.30, Runtime 114.0.1823.32)
    label: If it's regression, last working version
  validations:
    required: false
