name: Bug Report
title: '[Bug]: '
description: File a bug report
labels: ["bug"]
body:
- type: markdown
  attributes:
    value: 
      Thanks for taking the time to fill out this bug report. It will greatly assist us in accurately identifying the issue. Here is a [good sample report](https://github.com/MicrosoftEdge/WebView2Feedback/issues/3642)
- id: what-happened
  type: textarea
  attributes:
    description: Please tell us what's not working as expected. Please include callstacks and error messages if possible.
    label: What happened?
    placeholder: Please describe the issue you encountered. Callstacks and error messages are helpful.
  validations:
    required: true
- id: importance
  type: checkboxes
  attributes:
     label: Importance
     description: May you help us understand the level of importance of this ask to you?
     options:
       - label: Blocking. My app's basic functions cannot work.
       - label: Important. My app's user experience is significantly compromised.
       - label: Moderate. This issue has a certain impact on my app. 
  validations:
      required: true
- type: markdown
  attributes:
    value: |
        **Tip:** it's recommended to test your web content in the WebView2 control against Microsoft Edge Insider (preview) Channels (Beta, Dev, or Canary). [Download here](https://www.microsoft.com/en-us/edge/download/insider?form=MA13FJ). For more information please checkout the [development best practices](https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/developer-guide#run-compatibility-tests-regularly-when-using-the-evergreen-runtime).
- id: runtime-channel
  type: checkboxes
  attributes:
     label: Runtime Channel
     description: Are you using stable release or prerelease of WebView2 runtime?
     options:
       - label: Stable release 
       - label: Prerelease (Canary/Dev/Beta)      
  validations:
      required: true

- id: runtime-version
  type: input
  attributes:
    description: Please enter the Runtime version you are using. (e.g. 114.0.1823.79)
    label: Runtime Version
  validations:
    required: true
- id: sdk-version
  type: input
  attributes:
    description: Please enter the SDK version you are using. (e.g. 1.0.1905-prerelease)
    label: SDK Version
  validations:
    required: true

- id: framework
  type: dropdown
  attributes:
    description: What framework are you using?
    label: Framework
    options:
    - Please select
    - WPF
    - Win32
    - Winform
    - UWP/WinUI2
    - WinUI3
    - Unity Plugin
    - Other
  validations:
    required: true
- id: os
  type: checkboxes
  attributes:
    description: What operating system are you using?
    label: Operating System
    options:
    - label: Windows 10
    - label: Windows 11
    - label: Earlier than Windows 10 (deprecated)
    - label: Windows Server
    - label: Xbox
    - label: Hololens
    - label: Other
  validations:
    required: true
- id: os-version
  type: input
  attributes:
    description: Please enter the OS version you are using. (e.g., 22H2, 21H1, etc.)
    label: OS Version
  validations:
    required: false
- id: repro-steps
  type: textarea
  attributes:
    description: Minimal steps needed to reproduce the bug. Please be clear on what the expected behavior is vs. what the actual behavior is. Please provide a minimal sample app that demonstrates the issue, if possible.
    label: Repro steps and sample app
    placeholder: Please let us know how to reproduce this bug. A sample app would be very helpful. 
  validations:
    required: false
- id: regression
  type: dropdown
  attributes:
    description: Was this working before, but has regressed?
    label: Regression
    options:
    - No, this never worked
    - Regression in Runtime
    - Regression in SDK
    - Don't know
  validations:
    required: true
- id: last-working-version
  type: input
  attributes:
    description: If this is a regression, what was the last working version of SDK and Runtime? (e.g. SDK 1.0.1774.30, Runtime 114.0.1823.32)
    label: Last working version (if regression)
  validations:
    required: false
