name: Feature Request
description: Share your idea for a new feature/API enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: 
        Thanks for taking the time to fill out this feature request. Here is a [good sample report](https://github.com/MicrosoftEdge/WebView2Feedback/issues/3648)

  - type: textarea
    id: feature-need
    attributes:
      label: Why do you need this feature?
      description: Please help us understand why you need this feature. It would be great to briefly introduce what kind of app you are building, examples of the scenario/use cases you are trying to accomplish.
      placeholder: e.g. I'm building an video-editing app, and I need to do xyz when ... but I'm having trouble achieving this because... 
    validations:
      required: true

  - type: dropdown
    id: importance
    attributes:
      label: Importance
      description: May you help us understand the importance of this ask to you?
      options:
        - ----Please select----
        - Critical. My app's basic functions wouldn't work without it.
        - Impactful. My app's user experience would be significantly compromised without it.
        - Nice to have. There're other ways to tackle this, but having official API support would be beneficial.
    validations:
      required: true

  - type: dropdown
    id: timeline
    attributes:
      label: Timeline
      description: Any pending timeline for your app that depend on this particular ask?
      options:
        - ----Please select----
        - Within the next 6 months
        - Within 1 year
        - Within the next 1-2 years
        - To be determined
        - Not time-sensitive
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution and workaround
      description: Describe the solution you'd suggest, and workaround you've considered.
      placeholder: e.g. I've considered using... but it's not ideal because... I would suggest...
    validations:
      required: false



