name: Feature Request/API Enhancement
description: Suggest a new feature or enhancement for this project
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: app-introduction
    attributes:
      label: App Introduction
      description: May you briefly introduce what kind of app you are building?
    validations:
      required: false
  - type: textarea
    id: feature-need
    attributes:
      label: Feature Need
      description: May you help us understand why you need this feature? And some examples of the scenario/use cases you are trying to accomplish?
    validations:
      required: true
  - type: textarea
    id: existing-api
    attributes:
      label: Existing API
      description: Does this API/enhancement already exist in another WebView-like product (WebBrowser, CEF, etc.)?
    validations:
      required: false
  - type: textarea
    id: workaround
    attributes:
      label: Workaround
      description: Any workaround you are using currently?
    validations:
      required: false
  - type: checkboxes
    id: importance
    attributes:
      label: Importance
      description: May you help us understand the importance of this ask to you?
      options:
        - label: Blocking issue. My app's basic functions wouldn't work without this.
        - label: Impactful. My app's user experience would be significantly compromised.
        - label: Nice to have. There're other ways to tackle this, but would be good if there're official API support.
    validations:
      required: true
  - type: checkboxes
    id: development-phase
    attributes:
      label: Development Phase
      description: Would you mind sharing which development phase your app is at?
      options:
        - label: Has a enterprise user base
        - label: Has a consumer user base
        - label: Haven't released yet but has commitment
        - label: Just exploring and future release plan TBD
    validations:
      required: true

